/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Set = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'category' : IDL.Text,
  'muscleGroup' : IDL.Text,
});
export const WorkoutEntry = IDL.Record({
  'sets' : IDL.Vec(Set),
  'exercise' : Exercise,
});
export const UserProfile = IDL.Record({
  'fitnessGoal' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const ProgressStats = IDL.Record({
  'totalVolume' : IDL.Float64,
  'totalWorkouts' : IDL.Nat,
  'totalPlans' : IDL.Nat,
});
export const Workout = IDL.Record({
  'entries' : IDL.Vec(WorkoutEntry),
  'timestamp' : IDL.Int,
});
export const WorkoutHistory = IDL.Record({
  'workouts' : IDL.Vec(Workout),
  'totalVolume' : IDL.Float64,
});
export const WorkoutPlan = IDL.Record({
  'days' : IDL.Nat,
  'name' : IDL.Text,
  'dailyWorkouts' : IDL.Vec(IDL.Vec(WorkoutEntry)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWorkoutPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Vec(WorkoutEntry))],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getProgressStats' : IDL.Func([], [IDL.Opt(ProgressStats)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutHistory' : IDL.Func([], [IDL.Opt(WorkoutHistory)], ['query']),
  'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkout' : IDL.Func([IDL.Vec(WorkoutEntry)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Set = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'category' : IDL.Text,
    'muscleGroup' : IDL.Text,
  });
  const WorkoutEntry = IDL.Record({
    'sets' : IDL.Vec(Set),
    'exercise' : Exercise,
  });
  const UserProfile = IDL.Record({
    'fitnessGoal' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const ProgressStats = IDL.Record({
    'totalVolume' : IDL.Float64,
    'totalWorkouts' : IDL.Nat,
    'totalPlans' : IDL.Nat,
  });
  const Workout = IDL.Record({
    'entries' : IDL.Vec(WorkoutEntry),
    'timestamp' : IDL.Int,
  });
  const WorkoutHistory = IDL.Record({
    'workouts' : IDL.Vec(Workout),
    'totalVolume' : IDL.Float64,
  });
  const WorkoutPlan = IDL.Record({
    'days' : IDL.Nat,
    'name' : IDL.Text,
    'dailyWorkouts' : IDL.Vec(IDL.Vec(WorkoutEntry)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWorkoutPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Vec(WorkoutEntry))],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getProgressStats' : IDL.Func([], [IDL.Opt(ProgressStats)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutHistory' : IDL.Func([], [IDL.Opt(WorkoutHistory)], ['query']),
    'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkout' : IDL.Func([IDL.Vec(WorkoutEntry)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };