/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'name' : string,
  'category' : string,
  'muscleGroup' : string,
}
export interface ProgressStats {
  'totalVolume' : number,
  'totalWorkouts' : bigint,
  'totalPlans' : bigint,
}
export interface Set { 'weight' : number, 'reps' : bigint }
export interface UserProfile {
  'fitnessGoal' : [] | [string],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'entries' : Array<WorkoutEntry>,
  'timestamp' : bigint,
}
export interface WorkoutEntry { 'sets' : Array<Set>, 'exercise' : Exercise }
export interface WorkoutHistory {
  'workouts' : Array<Workout>,
  'totalVolume' : number,
}
export interface WorkoutPlan {
  'days' : bigint,
  'name' : string,
  'dailyWorkouts' : Array<Array<WorkoutEntry>>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExercise' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWorkoutPlan' : ActorMethod<
    [string, bigint, Array<Array<WorkoutEntry>>],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExerciseLibrary' : ActorMethod<[], Array<Exercise>>,
  'getProgressStats' : ActorMethod<[], [] | [ProgressStats]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutHistory' : ActorMethod<[], [] | [WorkoutHistory]>,
  'getWorkoutPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkout' : ActorMethod<[Array<WorkoutEntry>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];