/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Set = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'category' : IDL.Text,
  'muscleGroup' : IDL.Text,
});
export const WorkoutEntry = IDL.Record({
  'sets' : IDL.Vec(Set),
  'exercise' : Exercise,
});
export const ProgressStats = IDL.Record({
  'totalVolume' : IDL.Float64,
  'totalWorkouts' : IDL.Nat,
  'totalPlans' : IDL.Nat,
});
export const Workout = IDL.Record({
  'entries' : IDL.Vec(WorkoutEntry),
  'timestamp' : IDL.Int,
});
export const WorkoutHistory = IDL.Record({
  'workouts' : IDL.Vec(Workout),
  'totalVolume' : IDL.Float64,
});
export const WorkoutPlan = IDL.Record({
  'days' : IDL.Nat,
  'name' : IDL.Text,
  'dailyWorkouts' : IDL.Vec(IDL.Vec(WorkoutEntry)),
});

export const idlService = IDL.Service({
  'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createWorkoutPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Vec(WorkoutEntry))],
      [],
      [],
    ),
  'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getProgressStats' : IDL.Func([], [ProgressStats], ['query']),
  'getWorkoutHistory' : IDL.Func([], [WorkoutHistory], ['query']),
  'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'logWorkout' : IDL.Func([IDL.Vec(WorkoutEntry)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Set = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'category' : IDL.Text,
    'muscleGroup' : IDL.Text,
  });
  const WorkoutEntry = IDL.Record({
    'sets' : IDL.Vec(Set),
    'exercise' : Exercise,
  });
  const ProgressStats = IDL.Record({
    'totalVolume' : IDL.Float64,
    'totalWorkouts' : IDL.Nat,
    'totalPlans' : IDL.Nat,
  });
  const Workout = IDL.Record({
    'entries' : IDL.Vec(WorkoutEntry),
    'timestamp' : IDL.Int,
  });
  const WorkoutHistory = IDL.Record({
    'workouts' : IDL.Vec(Workout),
    'totalVolume' : IDL.Float64,
  });
  const WorkoutPlan = IDL.Record({
    'days' : IDL.Nat,
    'name' : IDL.Text,
    'dailyWorkouts' : IDL.Vec(IDL.Vec(WorkoutEntry)),
  });
  
  return IDL.Service({
    'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createWorkoutPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Vec(WorkoutEntry))],
        [],
        [],
      ),
    'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getProgressStats' : IDL.Func([], [ProgressStats], ['query']),
    'getWorkoutHistory' : IDL.Func([], [WorkoutHistory], ['query']),
    'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'logWorkout' : IDL.Func([IDL.Vec(WorkoutEntry)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };